apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  selector:
    app: weather-app  # Match the label of your pod (use your pod label here)
  ports:
    - protocol: TCP
      port: 80  # Expose on port 80
      targetPort: 5050  # Map to the Flask port inside the pod
  type: ClusterIP  # Internal service only accessible within the cluster
