name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}      # Docker Hub username (your email/username)
          password: ${{ secrets.DOCKER_PASSWORD }}      # Docker Hub access token (not Google password)

      - name: Build the Docker image
        run: docker build -t your-dockerhub-username/python-httpd-weather .

      - name: Push the Docker image to Docker Hub
        run: docker push your-dockerhub-username/python-httpd-weather:latest
